/**
 * Claritas - Readability + Defuddle Rust Port
 *
 * Node.js bindings for the Rust implementation.
 */

// Import native bindings
// The .node file is generated by napi-rs build
import { createRequire } from 'module';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Try to load the native module
let nativeModule: NativeModule;

interface NativeModule {
  extractReadability(html: string, url: string | null | undefined): Article | null;
  isProbablyReaderable(html: string): boolean;
}

try {
  // In development, the .node file is in the package root
  // In production, it's bundled with the package
  nativeModule = require('../claritas.node') as NativeModule;
} catch {
  try {
    // Try platform-specific path
    const platform = process.platform;
    const arch = process.arch;
    const modulePath = join(__dirname, '..', `claritas.${platform}-${arch}.node`);
    nativeModule = require(modulePath) as NativeModule;
  } catch (e) {
    throw new Error(
      `Failed to load native module. Did you run 'pnpm build'? Error: ${e}`
    );
  }
}

/**
 * Article extracted from HTML content
 */
export interface Article {
  /** The article title */
  title: string;
  /** The article author/byline */
  byline: string | null;
  /** The article HTML content */
  content: string;
  /** The article text content (no HTML) */
  textContent: string | null;
  /** Length of the text content */
  length: number;
  /** Short excerpt/description */
  excerpt: string | null;
  /** Site name from metadata */
  siteName: string | null;
  /** Text direction (ltr/rtl) */
  dir: string | null;
  /** Language code */
  lang: string | null;
}

/**
 * Options for readability extraction
 */
export interface ReadabilityOptions {
  /** Base URL for resolving relative links */
  url?: string;
}

/**
 * Extract readable content from HTML.
 *
 * @param html - The HTML content to parse
 * @param options - Optional configuration
 * @returns The extracted article or null if extraction failed
 *
 * @example
 * ```ts
 * const article = extractReadability('<html>...</html>', { url: 'https://example.com' });
 * if (article) {
 *   console.log(article.title);
 *   console.log(article.content);
 * }
 * ```
 */
export function extractReadability(
  html: string,
  options?: ReadabilityOptions
): Article | null {
  return nativeModule.extractReadability(html, options?.url ?? null);
}

/**
 * Check if a document is probably readable.
 *
 * This is a fast heuristic check that can be used to determine
 * whether it's worth running the full extraction.
 *
 * @param html - The HTML content to check
 * @returns true if the document appears to be readable
 *
 * @example
 * ```ts
 * if (isProbablyReaderable(html)) {
 *   const article = extractReadability(html);
 * }
 * ```
 */
export function isProbablyReaderable(html: string): boolean {
  return nativeModule.isProbablyReaderable(html);
}

// Re-export for convenience
export default {
  extractReadability,
  isProbablyReaderable,
};
